import { randomUUID } from 'node:crypto';
import type { JsonValue } from './canonical-json.js';
import { DomainEventStore } from './domain-event-store.js';
import type { SqliteDatabase } from './sqlite.js';

export type ProjectMembershipRole = 'accountable_human' | 'coordinator_twin' | 'collaborating_human' | 'collaborator_twin' | 'digital_assistant' | 'temporary_specialist' | 'external_expert';
export type SopScope = 'private' | 'project' | 'department' | 'organization';
export type EvaluationVerdict = 'passed' | 'failed' | 'inconclusive';
export interface ProjectRecord { id: string; tenantId: string; title: string; goal: string; accountableHumanId: string; coordinatorTwinId: string; status: string; memberCount: number; activeAssignmentCount: number; createdAt: string; updatedAt: string }
export interface ProjectMembershipRecord { id: string; projectId: string; actorRef: string; role: ProjectMembershipRole; scope: string; joinedAt: string; expiresAt: string | null; status: string }
export interface WorkerAssignmentRecord { id: string; projectId: string; employeeId: string; sponsorHumanId: string; permissionScope: string; expiresAt: string; status: string; releasedAt: string | null }
export interface BadCaseRecord { id: string; projectId: string; workOrderId: string | null; trajectoryRef: string; reportedBy: string; failedCriteria: string; status: string; createdAt: string }
export interface SopRevisionRecord { id: string; projectId: string; badCaseId: string; targetActorRef: string; baseVersion: string; candidateVersion: string; diff: string; scope: SopScope; status: string; promotedScope: SopScope | null; createdAt: string; promotedAt: string | null }
export interface EvaluationRecord { id: string; projectId: string; sopRevisionId: string; sourceRunId: string; candidateRunId: string; criteria: string; metrics: JsonValue; verdict: EvaluationVerdict; createdAt: string }
export interface ProjectGrowthChain { badCases: BadCaseRecord[]; revisions: SopRevisionRecord[]; evaluations: EvaluationRecord[] }
export interface CreateProjectInput { tenantId: string; actorRef: string; title: string; goal: string; accountableHumanId: string; coordinatorTwinId: string; collaborators: Array<{ humanUserId: string; twinId: string }>; assignments: Array<{ employeeId: string; sponsorHumanId: string; permissionScope: string; expiresAt: string; workOrderId?: string }>; idempotencyKey: string }
export interface RecordBadCaseInput { tenantId: string; projectId: string; workOrderId?: string; trajectoryRef: string; reportedBy: string; failedCriteria: string; idempotencyKey: string }
export interface CreateSopRevisionInput { tenantId: string; projectId: string; badCaseId: string; targetActorRef: string; baseVersion: string; candidateVersion: string; diff: string; scope: SopScope; actorRef: string; idempotencyKey: string }
export interface RecordEvaluationInput { tenantId: string; projectId: string; sopRevisionId: string; sourceRunId: string; candidateRunId: string; criteria: string; metrics: JsonValue; verdict: EvaluationVerdict; actorRef: string; idempotencyKey: string }
export interface PromoteSopRevisionInput { tenantId: string; projectId: string; sopRevisionId: string; promotionScope: SopScope; actorRef: string; idempotencyKey: string }

interface ProjectRow { id: string; tenant_id: string; title: string; goal: string; accountable_human_id: string; coordinator_twin_id: string; status: string; created_at: string; updated_at: string; member_count: number; active_assignment_count: number }
interface MembershipRow { id: string; project_id: string; actor_ref: string; role: ProjectMembershipRole; scope: string; joined_at: string; expires_at: string | null; status: string }
interface AssignmentRow { id: string; project_id: string; employee_id: string; sponsor_human_id: string; permission_scope: string; expires_at: string; status: string; released_at: string | null }
interface BadCaseRow { id: string; project_id: string; work_order_id: string | null; trajectory_ref: string; reported_by: string; failed_criteria: string; status: string; created_at: string }
interface RevisionRow { id: string; project_id: string; bad_case_id: string; target_actor_ref: string; base_version: string; candidate_version: string; diff: string; scope: SopScope; status: string; promoted_scope: SopScope | null; created_at: string; promoted_at: string | null }
interface EvaluationRow { id: string; project_id: string; sop_revision_id: string; source_run_id: string; candidate_run_id: string; criteria: string; metrics_json: string; verdict: EvaluationVerdict; created_at: string }

export class ProjectStore {
  private readonly events: DomainEventStore;
  constructor(private readonly database: SqliteDatabase, private readonly now: () => Date = () => new Date()) { this.events = new DomainEventStore(database); }

  create(input: CreateProjectInput): ProjectRecord {
    required(input.title, 'Project title'); required(input.goal, 'Project goal');
    return this.database.transaction(() => {
      const existing = this.database.prepare('SELECT id FROM projects WHERE tenant_id = ? AND title = ? AND accountable_human_id = ?').get<{ id: string }>(input.tenantId, input.title.trim(), input.accountableHumanId);
      if (existing) return this.requireProject(input.tenantId, existing.id);
      this.assertPair(input.tenantId, input.accountableHumanId, input.coordinatorTwinId);
      const now = this.now().toISOString(); const id = idFor('project');
      this.database.prepare("INSERT INTO projects (id, tenant_id, title, goal, accountable_human_id, coordinator_twin_id, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, 'active', ?, ?)").run(id, input.tenantId, input.title.trim(), input.goal.trim(), input.accountableHumanId, input.coordinatorTwinId, now, now);
      this.membership(input.tenantId, id, `human:${input.accountableHumanId}`, 'accountable_human', 'project.accept', now, null);
      this.membership(input.tenantId, id, `twin:${input.coordinatorTwinId}`, 'coordinator_twin', 'project.coordinate', now, null);
      for (const collaborator of input.collaborators) { this.assertPair(input.tenantId, collaborator.humanUserId, collaborator.twinId); this.membership(input.tenantId, id, `human:${collaborator.humanUserId}`, 'collaborating_human', 'project.contribute', now, null); this.membership(input.tenantId, id, `twin:${collaborator.twinId}`, 'collaborator_twin', 'project.coordinate', now, null); }
      for (const assignment of input.assignments) this.assignment(input.tenantId, id, assignment, now);
      this.event(input.tenantId, 'project', id, 'project.created', input.actorRef, input.idempotencyKey, { title: input.title.trim(), goal: input.goal.trim(), accountableHumanId: input.accountableHumanId, coordinatorTwinId: input.coordinatorTwinId });
      return this.requireProject(input.tenantId, id);
    })();
  }

  list(tenantId: string): ProjectRecord[] { return this.projects('WHERE p.tenant_id = ? ORDER BY p.created_at DESC, p.id', tenantId); }
  get(tenantId: string, projectId: string): ProjectRecord | undefined { return this.projects('WHERE p.tenant_id = ? AND p.id = ?', tenantId, projectId)[0]; }
  listMemberships(tenantId: string, projectId: string): ProjectMembershipRecord[] { this.requireProject(tenantId, projectId); return this.database.prepare('SELECT id, project_id, actor_ref, role, scope, joined_at, expires_at, status FROM project_memberships WHERE tenant_id = ? AND project_id = ? ORDER BY joined_at, id').all<MembershipRow>(tenantId, projectId).map((r) => ({ id: r.id, projectId: r.project_id, actorRef: r.actor_ref, role: r.role, scope: r.scope, joinedAt: r.joined_at, expiresAt: r.expires_at, status: r.status })); }
  listAssignments(tenantId: string, projectId: string): WorkerAssignmentRecord[] { this.requireProject(tenantId, projectId); return this.database.prepare('SELECT id, project_id, employee_id, sponsor_human_id, permission_scope, expires_at, status, released_at FROM worker_assignments WHERE tenant_id = ? AND project_id = ? ORDER BY created_at, id').all<AssignmentRow>(tenantId, projectId).map(mapAssignment); }

  releaseExpiredAssignments(tenantId: string, at = this.now().toISOString()): number {
    return this.database.transaction(() => {
      const expired = this.database.prepare("SELECT id, project_id, employee_id FROM worker_assignments WHERE tenant_id = ? AND status = 'active' AND expires_at <= ?").all<{ id: string; project_id: string; employee_id: string }>(tenantId, at);
      for (const item of expired) { this.database.prepare("UPDATE worker_assignments SET status = 'expired', released_at = ? WHERE id = ?").run(at, item.id); this.database.prepare("UPDATE project_memberships SET status = 'expired' WHERE tenant_id = ? AND project_id = ? AND actor_ref = ? AND role IN ('digital_assistant', 'temporary_specialist')").run(tenantId, item.project_id, `employee:${item.employee_id}`); this.event(tenantId, 'worker_assignment', item.id, 'worker_assignment.expired', 'system:assignment-reaper', `expiry-${item.id}-${at}`, { projectId: item.project_id, employeeId: item.employee_id, expiredAt: at }); }
      return expired.length;
    })();
  }

  recordBadCase(input: RecordBadCaseInput): BadCaseRecord { return this.database.transaction(() => { this.requireProject(input.tenantId, input.projectId); const id = idFor('badcase'); const now = this.now().toISOString(); this.database.prepare("INSERT INTO bad_cases (id, tenant_id, project_id, work_order_id, trajectory_ref, reported_by, failed_criteria, status, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, 'open', ?)").run(id, input.tenantId, input.projectId, input.workOrderId ?? null, input.trajectoryRef, input.reportedBy, input.failedCriteria, now); this.event(input.tenantId, 'bad_case', id, 'bad_case.recorded', input.reportedBy, input.idempotencyKey, { projectId: input.projectId, trajectoryRef: input.trajectoryRef, failedCriteria: input.failedCriteria }); return this.badCase(input.tenantId, id); })(); }
  createSopRevision(input: CreateSopRevisionInput): SopRevisionRecord { return this.database.transaction(() => { this.requireProject(input.tenantId, input.projectId); this.badCase(input.tenantId, input.badCaseId); const id = idFor('sop'); const now = this.now().toISOString(); this.database.prepare("INSERT INTO sop_revisions (id, tenant_id, project_id, bad_case_id, target_actor_ref, base_version, candidate_version, diff, scope, status, promoted_scope, created_at, promoted_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'candidate', NULL, ?, NULL)").run(id, input.tenantId, input.projectId, input.badCaseId, input.targetActorRef, input.baseVersion, input.candidateVersion, input.diff, input.scope, now); this.event(input.tenantId, 'sop_revision', id, 'sop_revision.created', input.actorRef, input.idempotencyKey, { projectId: input.projectId, badCaseId: input.badCaseId, candidateVersion: input.candidateVersion, scope: input.scope }); return this.revision(input.tenantId, id); })(); }
  recordEvaluation(input: RecordEvaluationInput): EvaluationRecord { return this.database.transaction(() => { this.requireProject(input.tenantId, input.projectId); this.revision(input.tenantId, input.sopRevisionId); const id = idFor('evaluation'); const now = this.now().toISOString(); this.database.prepare('INSERT INTO evaluations (id, tenant_id, project_id, sop_revision_id, source_run_id, candidate_run_id, criteria, metrics_json, verdict, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(id, input.tenantId, input.projectId, input.sopRevisionId, input.sourceRunId, input.candidateRunId, input.criteria, JSON.stringify(input.metrics), input.verdict, now); this.event(input.tenantId, 'evaluation', id, 'evaluation.recorded', input.actorRef, input.idempotencyKey, { projectId: input.projectId, sopRevisionId: input.sopRevisionId, sourceRunId: input.sourceRunId, candidateRunId: input.candidateRunId, verdict: input.verdict }); return this.evaluation(input.tenantId, id); })(); }
  promoteSopRevision(input: PromoteSopRevisionInput): SopRevisionRecord { return this.database.transaction(() => { const revision = this.revision(input.tenantId, input.sopRevisionId); if (revision.projectId !== input.projectId) throw new Error('SOP revision does not belong to project'); const evaluation = this.database.prepare("SELECT id FROM evaluations WHERE tenant_id = ? AND sop_revision_id = ? AND verdict = 'passed' LIMIT 1").get<{ id: string }>(input.tenantId, input.sopRevisionId); if (!evaluation) throw new Error('A passed evaluation is required before SOP promotion'); const now = this.now().toISOString(); this.database.prepare("UPDATE sop_revisions SET status = 'promoted', promoted_scope = ?, promoted_at = ? WHERE id = ?").run(input.promotionScope, now, input.sopRevisionId); this.event(input.tenantId, 'sop_revision', input.sopRevisionId, 'sop_revision.promoted', input.actorRef, input.idempotencyKey, { projectId: input.projectId, promotionScope: input.promotionScope, evaluationId: evaluation.id }); return this.revision(input.tenantId, input.sopRevisionId); })(); }
  getGrowthChain(tenantId: string, projectId: string): ProjectGrowthChain { this.requireProject(tenantId, projectId); return { badCases: this.database.prepare('SELECT id, project_id, work_order_id, trajectory_ref, reported_by, failed_criteria, status, created_at FROM bad_cases WHERE tenant_id = ? AND project_id = ? ORDER BY created_at, id').all<BadCaseRow>(tenantId, projectId).map(mapBadCase), revisions: this.database.prepare('SELECT id, project_id, bad_case_id, target_actor_ref, base_version, candidate_version, diff, scope, status, promoted_scope, created_at, promoted_at FROM sop_revisions WHERE tenant_id = ? AND project_id = ? ORDER BY created_at, id').all<RevisionRow>(tenantId, projectId).map(mapRevision), evaluations: this.database.prepare('SELECT id, project_id, sop_revision_id, source_run_id, candidate_run_id, criteria, metrics_json, verdict, created_at FROM evaluations WHERE tenant_id = ? AND project_id = ? ORDER BY created_at, id').all<EvaluationRow>(tenantId, projectId).map(mapEvaluation) }; }

  private membership(tenantId: string, projectId: string, actorRef: string, role: ProjectMembershipRole, scope: string, joinedAt: string, expiresAt: string | null): void { this.database.prepare("INSERT INTO project_memberships (id, tenant_id, project_id, actor_ref, role, scope, joined_at, expires_at, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'active')").run(idFor('projectmember'), tenantId, projectId, actorRef, role, scope, joinedAt, expiresAt); }
  private assignment(tenantId: string, projectId: string, input: CreateProjectInput['assignments'][number], now: string): void { const employee = this.database.prepare('SELECT id FROM digital_employees WHERE tenant_id = ? AND id = ?').get<{ id: string }>(tenantId, input.employeeId); if (!employee) throw new Error('Digital employee is unavailable in the current tenant'); if (Date.parse(input.expiresAt) <= Date.parse(now)) throw new TypeError('Temporary assistant expiry must be in the future'); const id = idFor('assignment'); this.database.prepare("INSERT INTO worker_assignments (id, tenant_id, project_id, work_order_id, employee_id, sponsor_human_id, permission_scope, expires_at, status, created_at, released_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'active', ?, NULL)").run(id, tenantId, projectId, input.workOrderId ?? null, input.employeeId, input.sponsorHumanId, input.permissionScope, input.expiresAt, now); this.membership(tenantId, projectId, `employee:${input.employeeId}`, 'digital_assistant', input.permissionScope, now, input.expiresAt); this.event(tenantId, 'worker_assignment', id, 'worker_assignment.created', `human:${input.sponsorHumanId}`, `assignment-${id}`, { projectId, employeeId: input.employeeId, permissionScope: input.permissionScope, expiresAt: input.expiresAt }); }
  private assertPair(tenantId: string, humanId: string, twinId: string): void { const pair = this.database.prepare("SELECT dt.id FROM digital_twins dt JOIN human_users hu ON hu.id = dt.owner_human_id WHERE dt.id = ? AND dt.tenant_id = ? AND dt.owner_human_id = ? AND dt.status = 'active' AND hu.status = 'active'").get<{ id: string }>(twinId, tenantId, humanId); if (!pair) throw new Error('Human and active twin must form a responsibility pair in the current tenant'); }
  private projects(where: string, ...values: unknown[]): ProjectRecord[] { return this.database.prepare(`SELECT p.id, p.tenant_id, p.title, p.goal, p.accountable_human_id, p.coordinator_twin_id, p.status, p.created_at, p.updated_at, (SELECT COUNT(*) FROM project_memberships pm WHERE pm.project_id = p.id AND pm.status = 'active') AS member_count, (SELECT COUNT(*) FROM worker_assignments wa WHERE wa.project_id = p.id AND wa.status = 'active') AS active_assignment_count FROM projects p ${where}`).all<ProjectRow>(...values).map(mapProject); }
  private requireProject(tenantId: string, projectId: string): ProjectRecord { const project = this.get(tenantId, projectId); if (!project) throw new Error('Project is unavailable in the current tenant'); return project; }
  private badCase(tenantId: string, id: string): BadCaseRecord { const row = this.database.prepare('SELECT id, project_id, work_order_id, trajectory_ref, reported_by, failed_criteria, status, created_at FROM bad_cases WHERE tenant_id = ? AND id = ?').get<BadCaseRow>(tenantId, id); if (!row) throw new Error('Bad case is unavailable in the current tenant'); return mapBadCase(row); }
  private revision(tenantId: string, id: string): SopRevisionRecord { const row = this.database.prepare('SELECT id, project_id, bad_case_id, target_actor_ref, base_version, candidate_version, diff, scope, status, promoted_scope, created_at, promoted_at FROM sop_revisions WHERE tenant_id = ? AND id = ?').get<RevisionRow>(tenantId, id); if (!row) throw new Error('SOP revision is unavailable in the current tenant'); return mapRevision(row); }
  private evaluation(tenantId: string, id: string): EvaluationRecord { const row = this.database.prepare('SELECT id, project_id, sop_revision_id, source_run_id, candidate_run_id, criteria, metrics_json, verdict, created_at FROM evaluations WHERE tenant_id = ? AND id = ?').get<EvaluationRow>(tenantId, id); if (!row) throw new Error('Evaluation is unavailable in the current tenant'); return mapEvaluation(row); }
  private event(tenantId: string, aggregateType: string, aggregateId: string, type: string, actorRef: string, correlationId: string, payload: JsonValue): void { this.events.append({ id: idFor('evt'), tenantId, aggregateType, aggregateId, type, occurredAt: this.now().toISOString(), actorRef, correlationId: `corr_${correlationId}`, payload }); }
}
function idFor(prefix: string): string { return `${prefix}_${randomUUID().replaceAll('-', '')}`; }
function required(value: string, label: string): void { if (!value.trim()) throw new TypeError(`${label} is required`); }
function mapProject(r: ProjectRow): ProjectRecord { return { id: r.id, tenantId: r.tenant_id, title: r.title, goal: r.goal, accountableHumanId: r.accountable_human_id, coordinatorTwinId: r.coordinator_twin_id, status: r.status, memberCount: r.member_count, activeAssignmentCount: r.active_assignment_count, createdAt: r.created_at, updatedAt: r.updated_at }; }
function mapAssignment(r: AssignmentRow): WorkerAssignmentRecord { return { id: r.id, projectId: r.project_id, employeeId: r.employee_id, sponsorHumanId: r.sponsor_human_id, permissionScope: r.permission_scope, expiresAt: r.expires_at, status: r.status, releasedAt: r.released_at }; }
function mapBadCase(r: BadCaseRow): BadCaseRecord { return { id: r.id, projectId: r.project_id, workOrderId: r.work_order_id, trajectoryRef: r.trajectory_ref, reportedBy: r.reported_by, failedCriteria: r.failed_criteria, status: r.status, createdAt: r.created_at }; }
function mapRevision(r: RevisionRow): SopRevisionRecord { return { id: r.id, projectId: r.project_id, badCaseId: r.bad_case_id, targetActorRef: r.target_actor_ref, baseVersion: r.base_version, candidateVersion: r.candidate_version, diff: r.diff, scope: r.scope, status: r.status, promotedScope: r.promoted_scope, createdAt: r.created_at, promotedAt: r.promoted_at }; }
function mapEvaluation(r: EvaluationRow): EvaluationRecord { return { id: r.id, projectId: r.project_id, sopRevisionId: r.sop_revision_id, sourceRunId: r.source_run_id, candidateRunId: r.candidate_run_id, criteria: r.criteria, metrics: JSON.parse(r.metrics_json) as JsonValue, verdict: r.verdict, createdAt: r.created_at }; }